import { GameAtom } from "@/atoms/GameAtom";
import { QuestionsAtom } from "@/atoms/QuestionsAtom";
import { Option } from "@/components/atoms/Select";
import { useAtom, useAtomValue } from "jotai";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Game() {
  const router = useRouter();
  const [game, setGame] = useAtom(GameAtom);
  const questions = useAtomValue(QuestionsAtom);

  const pageTitle = `TriviAle ${game.turn + 1}/${questions.length}`;

  const correctAnswers = game.questions.filter(
    (question) => question.correct
  ).length;
  const incorrectAnswers = game.questions.filter(
    (question) => !question.correct
  ).length;

  useEffect(() => {
    if (questions.length === 0) {
      router.push("/");
    }
  }, []);

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="game container">
        <div className="logo">
          <Image src="/logo.png" alt="logo" fill />
        </div>
        <p>{questions[game.turn].question}</p>
        <div>
          <span>{`${game.turn + 1}/${questions.length}`}</span>
          <span>{correctAnswers}</span>
          <span>{incorrectAnswers}</span>
        </div>
      </main>
    </>
  );
}
