import { Option } from "@/components/atoms/Select";
import { SearchForm } from "@/components/molecules/SearchForm";
import { GetServerSideProps, GetServerSidePropsResult } from "next";
import Head from "next/head";
import Image from "next/image";

type Props = {
  categories: Option[];
};

export default function Home(props: Props) {
  return (
    <>
      <Head>
        <title>TriviAle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="home container">
        <div className="logo">
          <Image src="/logo.png" alt="logo" fill />
        </div>
        <SearchForm categories={props.categories} />
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const categories = await fetch(
    `${process.env.NEXT_PUBLIC_URL}/api/categories`
  )
    .catch((err) => {
      console.error(err);
      throw new Error("Can not retrieve the categories");
    })
    .then((res) => res.json())
    .then((categories: Option[]) =>
      categories.sort((a, b) => a.text.localeCompare(b.text))
    );

  categories.unshift({
    value: "any",
    text: "Any category",
  });

  return {
    props: {
      categories,
    },
  };
};
