import { GameAtom } from "@/atoms/GameAtom";
import { useAtomValue } from "jotai";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { Stats as StatsComponent } from "@/components/molecules/Stats";
import { Button } from "@/components/atoms/Button";

export default function Stats() {
  const router = useRouter();
  const game = useAtomValue(GameAtom);

  useEffect(() => {
    if (game.questions.length === 0) {
      router.push("/");
    }
  }, []);

  return (
    <>
      <Head>
        <title>TriviAle stats</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="stats__page container">
        <div className="content">
          <div className="logo">
            <Image src="/logo.png" alt="logo" fill />
          </div>
          <StatsComponent />
        </div>
        <Button variant="play" onClick={() => router.push("/")}>
          Play again!
        </Button>
      </main>
    </>
  );
}
